kosmtik/kosmtik

src/Config.js, src/back/XRayTile.js, src/front/DataInspector.js, src/front/Sidebar.css
Produces a scrollable list of all available layers with checkboxes, looks like this:
=> Show checkboxes for individual layers in Data Inspector

src/Config.js
=> Fix config not defined for node v0.10.35

src/back/ProjectServer.js
If tolerance is included in the /query querystring params then this patch fixes the error when it encounters it as a string and not the expected integer. 
Example call to /query http://localhost:6789/osm-bright/query/9/52.44429203405363/-1.8731689453124998/?tolerance=300&layer=
The error looked like this:
```
/home/tim/projects/kosmtik/src/back/ProjectServer.js:169
var features = t.query(lon, lat, options);
^
TypeError: tolerance value must be a number
at doQuery (/home/tim/projects/kosmtik/src/back/ProjectServer.js:169:34)
at /home/tim/projects/kosmtik/src/back/ProjectServer.js:180:17
```
=> Fix for TypeError on tolerance parameter in query method

src/back/XRayTile.js
Patch to fix a seg fault seen in the data inspector layer if there is no data in the tile.
=> Fix for seg fault when a xray tile has no data refs #51

src/back/XRayTile.js
This Pull Request fixes an issue where if an xray tile has no data it will crash kosmtik. It is for issue #94
=> Fix for bug where xray tile with no data caused crash refs #94

.travis.yml
I added the `.travis.yml` file. It can run the tests.
The other purpose of this PR in the long run is also to add plugins installation tests as they fails depending of environment.
I should mention I already tested the configuration at https://travis-ci.org/ThomasG77/kosmtik where it fails due to some kosmtik tests not working ;)
=> Add .travis.yml to run tests

src/back/Project.js, src/back/ProjectServer.js, src/back/VectorBasedTile.js
Without this change, having buffers in vector tiles had no effect, because data outside the tile bounds was not used in rendering. This caused lots of cutoff labels.
=> Set map buffer size, and use when rendering vector tiles

src/Config.js
Because i never want to see the crosshairs. Added backendPolling to UserConfig because it seems like all the options should be settable in there.
=> read showCrosshairs and backendPolling from UserConfig

package.json
carto@0.16.0 is out officially.
=> upgrade carto to 0.16.0

src/plugins/base-exporters/front/export.js
rationale : 1, 2, 3, 4, 5 could be confused with zoom levels
=> use x1, x2 x3… instead of 1,2,3 in the ExportScaleChooser

src/back/VectorBasedTile.js, src/plugins/datasource-loader/index.js
This adds support for rendering when the max zoom for a style is greater than the max zoom for the vector tile source. Currently this is only supported for tilejson based sources.
=> Add support for overzoom rendering of vector tiles

src/plugins/base-exporters/index.js
bug found by @nebulon42 - https://github.com/kosmtik/kosmtik/issues/150#issuecomment-228179851
after change
```
mateusz@ugluk:~/Desktop/tmp/kosmtik$ node index.js export -help
[Core] Loading config from /home/mateusz/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Unable to load plugin kosmtik-map-compare MODULE_NOT_FOUND
[Core] → try: node index.js plugins --install kosmtik-map-compare
[Core] Unable to load plugin kosmtik-magnacarto MODULE_NOT_FOUND
[Core] → try: node index.js plugins --install kosmtik-magnacarto
'-p' expects a value
Usage: node index.js export [project] …
```
=> fix documentation - give the real name of parameter

package.json
Mapnik doesn't follow SemVer, and frequently something breaks in a new version.
=> Use an exact Mapnik version

src/back/Helpers.js
By default kosmtik was not sending a user-agent header, In debugging a tile server issue it was really helpful to be able to identify the kosmtik requests by greping.
=> Set user agent to kosmtik + version

src/back/loader/Base.js
This is needed to enable plugins that add support for additional source protocols
=> pass uri through for unknown source protocols

src/Config.js
So that newest Mapnik version is selected for Carto.
=> do not set Mapnik patch version to 0

README.md, package.json
Currently the process of installing, updating and using Kosmtik is a bit problematic for non-developers. This could be streamlined by using the power of NPM. As prerequisite we would need to move to regular releases and regular updates at the NPM registry. At the same time I would propose to drop the alpha version warning.
NPM allows to specify a `bin` property. When the package is installed globally the "binary" is linked into the path thus enabling `kosmtik serve ...` and the like instead of `node index.js serve ...`. Updating is also much easier. All you need to do is to call `npm install -g kosmtik` again.
The `preferGlobal` should print a warning that Kosmtik is best installed globally but it is still possible to install it locally.
**needs testing**
I have no idea how well that …
=> streamline CLI usage

package.json, src/back/PreviewServer.js
3.5.13 binary is not available:
```
$ http --headers 'https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.13/Release/node-v48-linux-x64.tar.gz'
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Date: Wed, 07 Dec 2016 08:50:38 GMT
Server: AmazonS3
Transfer-Encoding: chunked
x-amz-id-2: S4cqharLL/wfY5MiW15J89DLfjnJ6kZ+WrVOZ4AkE4Ane1k9dKxdrWinrPEvLb79iHfjhJeqbB8=
x-amz-request-id: 4E6592049D9889DC
```
While it's available for 3.5.14:
```
$ http --headers 'https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v48-linux-x64.tar.gz'
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 22145358
Content-Type: application/octet-stream
Date: Wed, 07 Dec 2016 08:50:58 GMT
ETag: "3b3c8c7a0892c672898125baf463b7a0"
Last-Modified: Fri, 09 Sep 2016 21:08:34 GMT
Server: AmazonS3 …
```
=> Bump node-mapnik to 3.5.14 to allow building with node LTS (6.x)

package.json, src/back/renderer/Carto.js
npm warned me about a bad package path for carto
** please note the change is untested**
npm WARN deprecated carto@0.15.3: This module is now under the @mapbox namespace: install @mapbox/carto instead
=> changed carto package path namespace

.travis.yml, package.json
Updating some dependencies that were reported as outdated.
Updating node versions for Travis, since older versions are now EOL (see https://github.com/nodejs/LTS for details).
=> update dependencies and node version for Travis

package.json
Necessary for handling scoped packages like carto.
Ref #215.
=> specify npm >= 1.5.0 as required 

package.json
The API in 3 has changed. This is the latest version in 2.x, and it works.
Fixes #219
=> Use generic-pool 2

src/plugins/local-config/index.js
=> do not show stack trace upon error in local config plugin

src/Config.js
Fixes #236.
When reading from an empty file the variable is `undefined` afterwards, which leads to an error.
=> add check for undefined config variable after reading from file

src/back/loader/Base.js
This is now deprecated in the MML definition. `id` should be used instead.
=> do not forcibly set layer name

README.md
By using a longitude outside of -90 to 90 you get a coordinate where lat and long cannot be transposed without an invalid coordinate.
This makes it clearer which is which in an example.
=> Change localconfig example location

src/front/Command.js
ctrl-shift-P is a Firefox built in (private mode).
We may make shortcuts customisable in the future, but let's make
it simple for now.
We keep the former one for recompatibility.
I've chosen ctrl-alt-P to keep something close and memorizable (P => palette), but I'm open to suggestions (YMMV… ;) ).
=> Change command palette shortcut to ctrl-alt-P

package.json
This is more important update than what the versioning says, because it bumps Mapnik from 3.0.18 to 3.0.20, which fixes this visible bug: https://github.com/mapnik/mapnik/pull/3844 (and also [some others too](
https://github.com/mapnik/mapnik/blob/v3.0.x/CHANGELOG.md)).
=> Update node-mapnik to 3.7.2

src/back/MetatileBasedTile.js, src/back/Project.js, src/back/ProjectServer.js, src/back/Tile.js, src/front/Map.js
Anyone for a review / test? :)
cc @nebulon42 @kent1D
=> Retina support

src/Config.js, src/back/Project.js, test/data/minimalist-project.xml
Hello!
I had an issue when using multiple project.mml with caching enabled.
When project.mml files are placed in single path (for example /path/style/project*.mml), then kosmtik uses "style" as prefix to path with cached metatiles.
In such case cache of multiple styles conflicts with each other.
This MR adds possibility to specify --style-name that will be used as prefix for cached metatiles, so now we are able to run multiple kosmtik instances in such way:
```bash
node /opt/kosmtik/index.js serve --mapnik-version 3.0.19 --style-name my_style --keep-cache --port 6790 /opt/mapnik/styles/project.mml
node /opt/kosmtik/index.js serve --mapnik-version 3.0.19 --style-name my_style_en --keep-cache --port 6791 /opt/mapnik/styles/project_en.mml
```
=> Adds option --style-name

.travis.yml
See https://nodejs.org/en/about/releases/
Node 6 is dead, node 8 is end of life.
Node 10 is LTS, and node 12 and 14 are current.
=> Travis CI: add Node 10, 12 and 14, remove Node 6

src/Config.js, src/back/ConfigEmitter.js, src/back/GeoUtils.js, src/back/Helpers.js, src/back/MetatileBasedTile.js, src/back/PluginsManager.js, src/back/PreviewServer.js, src/back/Project.js, src/back/ProjectServer.js, src/back/StateBase.js, src/back/Tile.js, src/back/Utils.js, src/back/VectorBasedTile.js, src/back/XRayTile.js, src/back/loader/Base.js, src/back/loader/MML.js, src/back/renderer/Carto.js, src/plugins/base-exporters/Base.js, src/plugins/base-exporters/MML.js, src/plugins/base-exporters/PNG.js, src/plugins/base-exporters/XML.js, src/plugins/base-exporters/YAML.js, src/plugins/base-exporters/index.js, src/plugins/datasource-loader/index.js, src/plugins/hash/index.js, src/plugins/local-config/index.js
*Preview the diff with whitespace disabled!* [direct link](https://github.com/kosmtik/kosmtik/pull/319/files?diff=split&w=1) 
Cleans up the definition of backend classes massively, by using the Javascript `class` syntax. This allows:
- `class A` instead of `.prototype`
- `constructor` and `super` instead of static calls to parent prototypes.
- `A extends B` instead of `util.extends(...)`
=> Use Javascript class syntax

src/Config.js, src/back/PluginsManager.js, src/plugins/version/index.js
This adds a command `version` that outputs the current package JSON version. This should solve #307. 
Output without any arguments:
```
[Core] No usable config file found in /home/hidde/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from ../plugins/version/index.js
command argument is required
Usage: /usr/bin/node index.js <command> [options]
command     
version     Show the package version
serve       Run the server
plugins     Manage plugins
export      Export a project
Options:
--port             Port to listen on.  [6789]
--host             Host to …
```
=> Add version plugin with version command

src/back/ProjectServer.js
Fix #329
When DataSource returns empty data for an x-ray tile, the XRayTile class doesn't execute the callback, this leads to a full hang.
=> Fix Data Inspector hang with empty data

package.json, test/fixtures.js
Loading the fonts appears to take > 1 second when running inside of GitHub Actions, but subsequent loads are much faster (< 10ms).  I'm not sure why this performance difference exists, but the disk cache is one theory.
Each test has a default timeout of 2 seconds which means that the first test which loads the fonts gets a large performance penalty and can sometimes fail due to timeout.
Increasing the timeouts of the tests may mask some actual performance issues.  So instead I suggest loading the fonts as part of a gobalSetup.
See:
https://mochajs.org/#global-setup-fixtures
Debugging commit which exposed performance information:
863f24cbfcb750ec5b946aaf3e2c757009703599
=> Prewarm the font cache before running any tests

.github/workflows/node.js.yml, package.json, test/tile.js
See https://nodejs.dev/en/about/releases/. Both 18 and 20 are LTS versions.
10.x, 12.x and 14.x can probably be removed because they are no longer supported.
=> Add Node 18 and 20 to CI, remove 10, 12 and 14

package.json, src/Config.js, src/back/MetatileBasedTile.js, src/back/Project.js, src/back/Tile.js, src/back/VectorBasedTile.js, src/back/XRayTile.js, src/plugins/base-exporters/PNG.js, test/tile.js
Small changes to get kosmtik up and running on OSX or Ubuntu
Updates dependency from mapnik to the up-to-date [@mapnik/mapnik](https://www.npmjs.com/package/@mapnik/mapnik), addresses issues with `node-pre-gyp` install in #354 , includes code from [this comment](https://github.com/kosmtik/kosmtik/issues/336#issuecomment-1176573218) to update tile / projection code
Suggestions for documentation: on Ubuntu, if there's an issue `connection to server on socket "/tmp/.s.PGSQL.5432" failed`, in the server's postgresql.conf you need to update `unix_socket_directories` to /tmp/  ( https://dba.stackexchange.com/questions/182189/how-do-i-access-postgres-when-i-get-an-error-about-var-run-postgresql-s-pgsql )
=> Update mapnik, projection for tiles
