- src/back/loader/Base.js
At least I assume this is what you meant - if not then the exporter test is broken.
> Fix evaluation order

- package.json
This fixes a regression with the colour mix function.
> upgrade carto to 0.16.1

- src/back/PluginsManager.js
example:
```
"kosmtik": {
"plugins": [ "kosmtik-fetch-remote", "kosmtik-place-search" ]
}
```
> Install the list of plugins required by project.mml

- src/back/PluginsManager.js
> No space between -- and install

- src/front/DataInspector.js
prevent an error when inspecting an item after many world tours "à la Moitessier" :)
> wrap lat/lon on click when data inspector is on

- src/back/ProjectServer.js
This allows options like Kosmtik + Tangram Play
> Enable CORS for vector tiles

- src/back/Tile.js
> honor scale factor in preview

- src/back/PreviewServer.js
- src/back/ProjectServer.js
This gives more control for plugins.
(This is actually a commit I forgot to push when working on https://github.com/kosmtik/kosmtik-places…)
> Also pass "request" to serverProjectRoute

- src/back/Tile.js
> Revert "honor scale factor in preview"

- src/back/MetatileBasedTile.js
> Fix metatiles being created in the wrong folder

- package.json
- src/front/MetatilesBounds.js
> Clean Metatilebounds

- src/back/Tile.js
> honor scale factor (take 2)

- src/back/Tile.js
Ref https://github.com/mapbox/carto/issues/269
> pass zoom level to Mapnik to allow usage of the zoom variable

- src/back/VectorBasedTile.js
This allows to disable vector tiles caching by adding this to the
user config (~/.config/kosmtik.yml):
cacheVectorTiles: false
cf #184
Next step is to make this controlable from the settings in the
UI.
> Add cacheVectorTiles global flag

- src/front/Core.css
- src/front/Toolbar.css
Corrected height of reload button, padding and alignment fixes.
> small cosmetic fixes for toolbar buttons

- src/back/Tile.js
> use scale=1 as fallback if scale is not defined in the mml

- src/front/Sidebar.css
> Fix large sidebar-content

- src/back/ProjectServer.js
This has two goals:
- .mss may not be in the same directory as the .mml/.yml (thus not on the
root dir, so they where not watched until now)
- we should only reload when .mss or .mml/.yml has changed (no need to watch
for README and such); question may be open for icons or data files, but until
now they were not taken into account (because usually in a subfolder) so we
can add this later
> Watch real file paths instead of project root

- src/front/Core.css
> Avoid zoom buttons on 2 lines

- package.json
Fixes three security advisories:
```
~/C/G/kosmtik (master|…) $ yarn audit 
yarn audit v1.22.5
warning mocha > json3@3.3.2: Please use the native JSON object instead of JSON 3
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.10.2 …
```
> Upgrade Mocka from v3 to v8

- package.json
Fixes two security advisories
```
~/C/G/kosmtik (upgrade-mocha|…) $ yarn audit
yarn audit v1.22.5
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ carto                                                        │ …
```
> Upgrade js-yaml

- README.md
> fix: correct the node version to v9.3.0

- src/plugins/base-exporters/PNG.js
Update bounding box reprojection to use ProjTransform
@yohanboniface @tomhughes @timwaters
> Fix export PNG (node-mapnik v4.6.9) 
